# Generated by Django 5.2.4 on 2025-07-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_flashsale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flashsale',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='flashsale',
            constraint=models.UniqueConstraint(fields=('book', 'start_time', 'end_time'), name='unique_flashsale_period'),
        ),
    ]
